server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://localhost:5173"
              - "http://localhost:8080"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowed-headers:
              - "*"
            allow-credentials: true
            max-age: 3600
            add-to-simple-request-headers: true
      routes:
        - id: user-service
          uri: lb://healthcare-user-service
          predicates:
            - Path=/api/users/**,/api/auth/**,/api/departments/**,/api/roles/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}
        - id: claim-service
          uri: lb://claim-service
          predicates:
            - Path=/api/claims/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/api/doctors/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}
        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/api/reports/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"